### ISSUE TITLE
Win10 异常

### ISSUE THREAD

**Issue by BluesYoung-web** [wll8/sys-shim#1]
## 环境

版本	Windows 10 专业版
版本号	21H2
安装日期	‎2022/‎7/‎5
操作系统内部版本	19044.3086
体验	Windows Feature Experience Pack 1000.19041.1000.0

## 操作流程

下载 release 中的 page.html 和 main.exe

运行 main.exe，自动安装了 webview2，然后窗口消失，再次运行，只存在于后台，看不见任何表现

下载 win12.exe，运行，无任何表现

下载 win11.exe，运行，无任何表现

删除 main.exe 及 page.html，运行 win12,win11 依旧无任何表现

重新下载 main.exe，无任何表现，也没有自动创建 page.html

**Comment by wll8** [comment]
先结束掉 main.exe 进程，再把单独的 main.exe 独自一个目录中试试:
``` bat
rem 结束进程的快捷命令
taskkill /f /im main.exe
```

如果还不行，尝试重启系统再试试，也许是安装了 webview 环境需要重启或安装的 webview 版本过新不兼容。

或者使用原语言提供的 webview 范例看看是否能运行：

[放弃 Electron，拥抱 WebView2！JavaScript 快速开发独立 EXE 程序](https://mp.weixin.qq.com/s?__biz=MzA3Njc1MDU0OQ==&mid=2650932568&idx=1&sn=e2ceb6ccc94fc8e689bc34c470feccc7&chksm=84aa2ee2b3dda7f4d982ebff32517abfac115c12b42eb5d3a7556b760d1347dcbd022b662c2a&scene=178&cur_album_id=2209804829378543621#rd)

**Comment by BluesYoung-web** [comment]
重启还是没用，可能是公司的电脑有绿盾吧，晚上回家拿自己的电脑试试
![0007DE48](https://github.com/wll8/sys-shim/assets/55608642/1a427019-1d9d-42af-8713-38bb36a422fa)

**Comment by wll8** [comment]
能摸鱼的话直接到 https://www.aardio.com/ 这里下载官方 IDE 试试，6mb，还是不错的。

**Comment by BluesYoung-web** [comment]
我自己的电脑就没问题

**Comment by wll8** [comment]
不知道是不是像你说的那样因为绿盾，像 360 有个网购模式。好像在这个模式下，所有没有证书的 exe 都不允许启动。
