### ISSUE TITLE
点击打包出来的 exe 文件时报 无法创建 main.exe

### ISSUE THREAD

**Issue by aMagicalpole** [wll8/sys-shim#10]
![image](https://github.com/user-attachments/assets/d993b3cf-4e88-4150-b0f1-ca0586b7640f)

使用 npx sys-shim pack --input http://localhost:5173 打包出来能正常访问

采用下面配置打包出来的产物则会报这个错误
```
"browserArguments": "--disable-web-security --allow-running-insecure-content ",
  "form": {
    "right": "1300",
    "bottom": "800"
  },
  "page": "index.html"
```

**Comment by aMagicalpole** [comment]
我将生成在 C:\Program Files (x86)\sys-shim-app 下的文件全部清空后重新运行就可以了

**Comment by wll8** [comment]
好的，有问题继续交流。
