### ISSUE TITLE
ws.call('run')如何回调？

### ISSUE THREAD

**Issue by JunwayGuo** [wll8/sys-shim#2]
例如process.popen执行cmd命令，无法获返回值

**Comment by wll8** [comment]
call 方法返回一个数组，第一项为代码是否运行错误，第二项为代码 return 的返回值。

示例：从命令行获取 git 版本。

``` js
var [err, gitStr]= await main.ws.call(`run`, [
`
  var prcs = process.popen("git -v") // 运行命令
  var text = prcs.readAll() // 读取命令所有输出
  return text // 把数据抛给 js
`])

console.log(gitStr) // git version 2.41.0.windows.1
```

> 图片：  
> ![image](https://github.com/wll8/sys-shim/assets/28223260/615ac953-3030-47bd-a391-5ea56f7750ce)



通过自定义 msg 订阅，也可以实现获取代码中的返回值。

示例：动态获取命令行输出。

```js
var msg = new window.main.Msg() // 创建一个消息实例
msg.on(`run_xxx`, (info) => { // 监听 run_xxx 发来的消息
  console.log(`info`, info)
})
await main.ws.call(`run`, [
  `
  var prcs = process.popen("ping 127.0.0.1")
  for( all,out,err in prcs.each() ){ // 动态读取命令输出
    G.rpcServer.publish("run_xxx", out, err) // 向 run_xxx 发送消息
  }
  `
])
```

> 图片：  
> ![image](https://github.com/wll8/sys-shim/assets/28223260/d847b7e6-6d6f-4f60-b067-bc4aa4f0cbaa)

**Comment by JunwayGuo** [comment]
感谢回复，按照示例的确可以拿到字返回的字符串。
但，当命令有误，或缺少环境变量，未能获取异常的回调

如在没有path变量时候，执行 `adb version`

控制台应返回
“
![image](https://github.com/wll8/sys-shim/assets/31336068/2e7d5107-512d-4df5-9ba7-27f953da0da0)
”

而process.popen返回的是 undefined

**Comment by wll8** [comment]
不客气，欢迎一起完善此项目。

1. 如果你说的是 js 里接收到的，那么它的错误只有在 ws.run 里的 code 有错误才会返回错误。
2. 如果你说的是 ws.run 里的代码里的 `process.popen`，那他没有 undefined，并且如果命令不存在，他的返回值为空（这是 aardio 的行为）
3. 如果你希望以 cmd 的行为回显错误，例如`adb 不是内部命令`，可以使用 `process.popen.cmd`

```js
await main.ws.call(`run`, [
`
  var prcs = process.popen.cmd("adb -v") // 运行命令
  var text = prcs.readAll() // 读取命令所有输出
  return text // 把数据抛给 js
`])
```
> 图片：  
> ![image](https://github.com/wll8/sys-shim/assets/28223260/87ee65c3-5941-44ab-a263-a1303ea71112)

**Comment by JunwayGuo** [comment]
感谢回复，我的问题已解决。
作者加油，希望不要放弃，完善一下。
我和你的困境一样，尝试过无数种方法，现在无奈用electron，如果搞定跨平台，这就是神器。
如果有需要，愿意加入团队，贡献代码。

**Comment by wll8** [comment]
那可真是太需要了！因为想写一些小工具又不想装一堆环境，所以弄了这东西。目前自己的小工具已实现。所以后面有新的小工具需求时，才会去继续完善此仓库代码。如果可以：

- 你有一个项目A，使用此工具来做（暂主要支持 win 平台），可以实现收益的话，我很乐意参与项目A的贡献。这样我能恰饭的同时，完善此工具的同时也在和你一起完善项目A。

- 如果后期需要跨平台，在通用 api 的项目上，对接相应平台的 bin 文件即可。

**Comment by JunwayGuo** [comment]
了解。
我目前可盈利的项目都有跨平台的需求。只能继续用Electron。
我近期打算开发一个小众需求的工具，并开源，使用你的框架，希望能帮助你推广。

**Comment by wll8** [comment]
好。有需要的操作系统API告诉我，我来封装。
