### ISSUE TITLE
Request：来个react版本

### ISSUE THREAD

**Issue by fantasticsoul** [wll8/sys-shim#4]
楼主威武，可以来个react版本的么

**Comment by wll8** [comment]
它与前端框架无关的哟，你可以使用前端框架或其他语言。比如说：你下载 main.exe，然后启动你的 react 开发服务，把开发服务的 url 告诉 main.exe，这下 main.exe 就会在你的 react 项目里注入 Sys 这个方法。然后你调用 Sys，即可调用操作系统的 API 。

例如这个项目就是 react 的：

下载地址：[win11.exe](https://github.com/wll8/sys-shim/releases/download/example/win11.exe)

![231203_163647](https://github.com/wll8/sys-shim/assets/28223260/f212a814-ce0e-4d30-8882-8d6f47aceaa8)

**Comment by fantasticsoul** [comment]
明白了，感谢提示
