### ISSUE TITLE
main.exe文件无法正常打开使用

### ISSUE THREAD

**Issue by ssuperjee** [wll8/sys-shim#9]
![f7f44a685465a2ba3640d50062590c6](https://github.com/user-attachments/assets/6067dee2-a943-4683-8d96-71f1dc081947)
运行命令生成main.exe文件之后 传给其他用户，显示的结果为上图，无法正常使用

**Comment by wll8** [comment]
1. 你运行的命令是什么？比如 `sys-shim pack --input https://www.baidu.com`，输出的不是 main.exe ，而是一个带时间标识的文件。
2. 如果直接运行 main.exe 效果就是这样的。因为它是前端代码与系统通信的桥梁。

一般是使用 sys-shim pack 打包成单文件发给别人，如果你是解压后发给别人，在 main.exe 目录也需要有对应的前端资源。


参考文章：https://juejin.cn/post/7373831659470880806

**Comment by ssuperjee** [comment]
好的。 解决了
